apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/namal1230/MERN-BE-Production.git"
    targetRevision: HEAD
    path: express-chart
    helm:
      releaseName: express-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: saas-app-backend # auto create namespace
  syncPolicy:
    automated:
      prune: true # Delete automatically
      selfHeal: true # Sync automatically
    syncOptions:
      - CreateNamespace=true
image:
  repository: namaldil/saas-backend
  tag: "1.0.0"
  pullPolicy: Always

imagePullSecrets:
  - name: my-registry-secret
