apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/namal1230/MERN-BE-Production.git"
    targetRevision: HEAD
    path: express-chart
    helm:
      releaseName: express-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
